#!/usr/bin/env node
/**
 * @shelchin/i18n v2.0 CLI - Type Generation
 *
 * Generates TypeScript type definitions from locale JSON files
 *
 * Usage:
 *   npx i18n generate-types [options]
 *
 * Options:
 *   --dir <path>     Locales directory (default: src/locales)
 *   --output <path>  Output file path (default: src/locales/i18n.d.ts)
 *   --watch          Watch for changes
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { realpathSync } from 'node:fs';
export interface GenerateTypesOptions {
	/** Locales directory path */
	dir: string;
	/** Output file path */
	output: string;
	/** Watch mode */
	watch?: boolean;
	/** Module name to augment (default: '@shelchin/i18n') */
	module?: string;
}

/** Plural suffixes that indicate a pluralized key */
const PLURAL_SUFFIXES = ['_zero', '_one', '_two', '_few', '_many', '_other'];

/**
 * Extract all translation keys from a JSON object
 */
function extractKeys(obj: Record<string, unknown>, prefix = ''): string[] {
	const keys: string[] = [];

	for (const [key, value] of Object.entries(obj)) {
		// Skip metadata
		if (key === '_meta') continue;

		const fullKey = prefix ? `${prefix}.${key}` : key;

		if (typeof value === 'string') {
			keys.push(fullKey);

			// Add base key for plural forms (e.g., items_one -> items)
			for (const suffix of PLURAL_SUFFIXES) {
				if (fullKey.endsWith(suffix)) {
					const baseKey = fullKey.slice(0, -suffix.length);
					keys.push(baseKey);
					break;
				}
			}
		} else if (typeof value === 'object' && value !== null) {
			keys.push(...extractKeys(value as Record<string, unknown>, fullKey));
		}
	}

	return keys;
}

/**
 * Recursively find all JSON files in a directory
 */
function findJsonFiles(dir: string, baseDir: string = dir): string[] {
	const files: string[] = [];

	if (!fs.existsSync(dir)) {
		return files;
	}

	const entries = fs.readdirSync(dir, { withFileTypes: true });

	for (const entry of entries) {
		const fullPath = path.join(dir, entry.name);
		if (entry.isDirectory()) {
			// Recursively scan subdirectories
			files.push(...findJsonFiles(fullPath, baseDir));
		} else if (entry.isFile() && entry.name.endsWith('.json')) {
			files.push(fullPath);
		}
	}

	return files;
}

/**
 * Read all JSON files in a locale directory (including subdirectories) and extract keys
 * Subdirectories are for organization only - namespace is the filename
 */
function extractKeysFromLocale(localeDir: string): Map<string, string[]> {
	const namespaceKeys = new Map<string, string[]>();

	if (!fs.existsSync(localeDir)) {
		return namespaceKeys;
	}

	const jsonFiles = findJsonFiles(localeDir);

	for (const filePath of jsonFiles) {
		// Use only the filename as namespace (ignore subdirectory structure)
		const namespace = path.basename(filePath, '.json');
		const content = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
		const keys = extractKeys(content);

		// Prefix keys with namespace
		const prefixedKeys = keys.map((k) => `${namespace}.${k}`);

		// Merge with existing keys if namespace already exists (from different subdirs)
		const existingKeys = namespaceKeys.get(namespace) || [];
		namespaceKeys.set(namespace, [...new Set([...existingKeys, ...prefixedKeys])]);
	}

	return namespaceKeys;
}

/**
 * Generate TypeScript type definitions
 */
export function generateTypes(options: GenerateTypesOptions): void {
	const { dir, output, module: moduleName = '@shelchin/i18n' } = options;

	// Find all locale directories
	if (!fs.existsSync(dir)) {
		console.error(`[i18n] Locales directory not found: ${dir}`);
		return;
	}

	const localeDirs = fs.readdirSync(dir).filter((f) => {
		const fullPath = path.join(dir, f);
		return fs.statSync(fullPath).isDirectory() && /^[a-z]{2}(-[A-Z]{2})?$/.test(f);
	});

	if (localeDirs.length === 0) {
		console.warn(`[i18n] No locale directories found in ${dir}`);
		return;
	}

	// Use first locale as reference for keys
	const referenceLocale = localeDirs[0];
	const referenceDir = path.join(dir, referenceLocale);
	const namespaceKeys = extractKeysFromLocale(referenceDir);

	// Collect all keys
	const allKeys = new Set<string>();
	for (const keys of namespaceKeys.values()) {
		keys.forEach((k) => allKeys.add(k));
	}

	// Generate type definition
	const sortedKeys = Array.from(allKeys).sort();

	const typeContent = `// This file is auto-generated by @shelchin/i18n CLI
// Do not edit manually

import '${moduleName}';

declare module '${moduleName}' {
  interface TranslationKeys {
${sortedKeys.map((k) => `    '${k}': string;`).join('\n')}
  }
}
`;

	// Write output file
	const outputDir = path.dirname(output);
	if (!fs.existsSync(outputDir)) {
		fs.mkdirSync(outputDir, { recursive: true });
	}

	fs.writeFileSync(output, typeContent, 'utf-8');
	console.log(`[i18n] Generated types: ${output} (${sortedKeys.length} keys)`);
}

/**
 * Watch mode - regenerate types on file changes
 */
export function watchTypes(options: GenerateTypesOptions): void {
	const { dir } = options;

	console.log(`[i18n] Watching for changes in ${dir}...`);

	// Initial generation
	generateTypes(options);

	// Watch for changes
	fs.watch(dir, { recursive: true }, (eventType, filename) => {
		if (filename?.endsWith('.json')) {
			console.log(`[i18n] Detected change in ${filename}, regenerating types...`);
			generateTypes(options);
		}
	});
}

// CLI entry point
function main(): void {
	const args = process.argv.slice(2);

	const options: GenerateTypesOptions = {
		dir: 'src/locales',
		output: 'src/locales/i18n.d.ts',
		watch: false,
		module: '@shelchin/i18n'
	};

	// Parse arguments
	for (let i = 0; i < args.length; i++) {
		const arg = args[i];

		if (arg === '--dir' && args[i + 1]) {
			options.dir = args[++i];
		} else if (arg === '--output' && args[i + 1]) {
			options.output = args[++i];
		} else if (arg === '--module' && args[i + 1]) {
			options.module = args[++i];
		} else if (arg === '--watch') {
			options.watch = true;
		} else if (arg === 'generate-types') {
			// Command name, ignore
		} else if (arg === '--help' || arg === '-h') {
			console.log(`
@shelchin/i18n CLI - Type Generation

Usage:
  npx i18n generate-types [options]

Options:
  --dir <path>      Locales directory (default: src/locales)
  --output <path>   Output file path (default: src/locales/i18n.d.ts)
  --module <name>   Module to augment (default: @shelchin/i18n)
  --watch           Watch for changes
  --help, -h        Show this help message
`);
			process.exit(0);
		}
	}

	if (options.watch) {
		watchTypes(options);
	} else {
		generateTypes(options);
	}
}

// Run if executed directly (ESM compatible)
const isMainModule = realpathSync(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMainModule) {
	main();
}
