// This file is auto-generated by @shelchin/i18n CLI
// Do not edit manually

import '@shelchin/i18n';

declare module '@shelchin/i18n' {
	interface TranslationKeys {
		'common.cancel': string;
		'common.currentLocale': string;
		'common.features.autoScan': string;
		'common.features.formatting': string;
		'common.features.lazyLoad': string;
		'common.features.minimal': string;
		'common.features.ssr': string;
		'common.features.svelte5': string;
		'common.features.typeSafe': string;
		'common.features.zeroDeps': string;
		'common.github.description': string;
		'common.github.star': string;
		'common.labels.count': string;
		'common.labels.name': string;
		'common.loading': string;
		'common.ok': string;
		'common.quickStart.install': string;
		'common.quickStart.setup': string;
		'common.quickStart.step1': string;
		'common.quickStart.step2': string;
		'common.quickStart.step3': string;
		'common.quickStart.step4': string;
		'common.quickStart.usage': string;
		'common.sections.basic': string;
		'common.sections.features': string;
		'common.sections.interpolation': string;
		'common.sections.locales': string;
		'common.sections.namespaces': string;
		'common.sections.pluralization': string;
		'common.sections.quickStart': string;
		'routes/about.backHome': string;
		'routes/about.content': string;
		'routes/about.description': string;
		'routes/about.title': string;
		'routes/home.description': string;
		'routes/home.faqs': string;
		'routes/home.faqs.0.answer': string;
		'routes/home.faqs.0.question': string;
		'routes/home.faqs.1.answer': string;
		'routes/home.faqs.1.question': string;
		'routes/home.faqs.2.answer': string;
		'routes/home.faqs.2.question': string;
		'routes/home.features': string;
		'routes/home.features.0': string;
		'routes/home.features.1': string;
		'routes/home.features.2': string;
		'routes/home.greeting': string;
		'routes/home.items': string;
		'routes/home.items_one': string;
		'routes/home.items_other': string;
		'routes/home.items_zero': string;
		'routes/home.title': string;
	}
}
